### ISSUE TITLE
Bug with function declaration highlighting

### ISSUE THREAD

**Issue by aviaryan** [ahkscript/SublimeAutoHotkey#16]
Not Highlighted

```
addToWinClip(lastEntry, extraTip)
{
```

**Comment by aviaryan** [comment]
Declarations where `{` is not on the same line as function declaration are not highlighted. 
I believe using `begin` and `end` regex patterns can fix it. `C++.tmLanguage` has done it the same way but I am not sure how to port that to AHK

**Comment by robertcollier4** [comment]
From my experimentation, it seems to be impossible to do this type of syntax highlighting for constructs spanning over multiple lines due to the RegEx parser in SublimeText configured to only apply rules on a line-by-line basis only.

Reference:
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=11537

    I believe that the regexes in .tmLanguage files are all single-line to improve parsing speed.
