### ISSUE TITLE
can't "Goto symbol"

### ISSUE THREAD

**Issue by lipkau** [ahkscript/SublimeAutoHotkey#43]
I am having trouble with the "Goto Symbol" functionallity
It works great in the majority of cases. But... in other, the list of symbols is empty.
One file where this happens, is tic's gdip.ahk

does this happen to any one else?

**Comment by robertcollier4** [comment]
"Goto Symbol" goes to lines matching "entity.name.function" syntax highlighting.

https://www.sublimetext.com/docs/3/scope_naming.html
"Function names receive one of the following scopes. These are included in the symbol list and index."

The reason that Gdip.ahk is not function declaration syntax highlighted is because the "{" is not on the same line as the function declaration. To make it work change the function declarations to include "{" on the same line such as `Functionname() {`.
Otherwise it is impossible to know if Functionname() is calling a function or is a function declaration.
