### ISSUE TITLE
add an extensive example file to the repo

### ISSUE THREAD

**Issue by lipkau** [ahkscript/SublimeAutoHotkey#44]
I have seen this in a lot of sublime language definition projects.
A large file with a collection of valid and invalid codes, in order to see what is working and what not.

In the [SublimeText/PowerShell](https://github.com/SublimeText/PowerShell/tree/dev/tests/samples), for example, tis file is only available in the "dev" branch

**Comment by robertcollier4** [comment]
I feel this would be superflous to a SublimeText package. The most important thing - is it working with YOUR script. There are lots of example files of AutoHotkey available on the net. Closing since the purpose of this Github is everyone to test this package on there script and report back there findings.
