### ISSUE TITLE
[Feature request] Compile and run

### ISSUE THREAD

**Issue by Kristinita** [ahkscript/SublimeAutoHotkey#45]
### 1. Request

It would be nice, if would be possible to compile and run AutoHotkey scripts, even if current file already run.

### 2. Justification

AutoHotkey user/developer will needs fewer steps, it will save his time.

### 3. Settings

I have a file `KristinitaSnippets.ahk`. Now I have in it more than 200 snippets, which I use several times per hour. Example snippet:

```autohotkey
:R*:/Кристина::Кристина изумительна!
```

Almost every day I update this file.

### 4. Steps to reproduce

I write new snippet in `KristinitaSnippets.ahk` file → I save file → I want run new `KristinitaSnippets.exe` file with my new changes.

### 5. Actual behavior

If `KristinitaSnippets.exe` process enable, <kbd>Ctrl+Shift+P</kbd> → `AutoHotkey compile` → compilation failed.

![Failed](http://i.imgur.com/DbQfbSs.png)

I need manually close `KristinitaSnippets.exe` process → <kbd>Ctrl+Shift+P</kbd> → `AutoHotkey — Compile` → <kbd>Ctrl+Shift+P</kbd> → `AutoHotkey — Run` → I can use my new snippets.

### 6. Desirable behavior

If `KristinitaSnippets.exe` process enable, <kbd>Ctrl+Shift+P</kbd> → `AutoHotkey: Compile And Run` → old `KristinitaSnippets.exe` process close → new `KristinitaSnippets.exe` process run → I can use my new snippets.

Thanks.

**Comment by robertcollier4** [comment]
This might not be useful to many people. Such are usually just using "#SingleInstance force" at the top of there script - have you thought about doing this?
If you really still wanted this and to not have "#SingleInstance force" take care of it - you could add to ahkexec.py and add the use of a exe killer utility such as pskill.exe.

**Comment by robertcollier4** [comment]
https://autohotkey.com/docs/commands/_SingleInstance.htm

**Comment by robertcollier4** [comment]
I feel this problem would be solved by running your script with the AutoHotkey.exe executable (.ahk) file instead of making a new .exe everyday. Exes are made usually for distribution and not for daily self use rebuilding. Perhaps use "Run" instead of "Compile" for your use. It would be faster. Process killing the executable before compiling it would require tracking the PID which would be quite difficult. Closing this issue. Consider "Running" your script daily with "SingleInstance force" instead of recompiling it daily. There is no need to compile your script ever unless you are distributing it - in which case you would only do this once.
